# Generated by Django 4.0.1 on 2022-01-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALEUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertypes',
            name='type_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
