# Generated by Django 4.0.1 on 2022-02-25 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ALEUser', '0007_alter_statistics_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actions',
            options={'verbose_name': 'Action', 'verbose_name_plural': 'Actions'},
        ),
        migrations.AlterModelOptions(
            name='decision',
            options={'verbose_name': 'Decision', 'verbose_name_plural': 'Decisions'},
        ),
        migrations.AlterModelOptions(
            name='decision_history',
            options={'verbose_name': 'Decision History', 'verbose_name_plural': 'Decision Histories'},
        ),
        migrations.AlterModelOptions(
            name='rules',
            options={'verbose_name': 'Rule', 'verbose_name_plural': 'Rules'},
        ),
        migrations.AlterModelOptions(
            name='rulestypes',
            options={'verbose_name': 'Rule Type', 'verbose_name_plural': 'Rule Types'},
        ),
        migrations.AlterModelOptions(
            name='settings_value',
            options={'verbose_name': 'Setting Value', 'verbose_name_plural': 'Setting Values'},
        ),
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name': 'Statistics', 'verbose_name_plural': 'Statistics'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='usertypes',
            options={'verbose_name': 'User Type', 'verbose_name_plural': 'User Types'},
        ),
    ]
