# Generated by Django 4.0.1 on 2022-04-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALEUser', '0008_alter_actions_options_alter_decision_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='decision',
            options={},
        ),
        migrations.AlterModelOptions(
            name='decision_history',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rules',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rulestypes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='settings_value',
            options={},
        ),
        migrations.AlterModelOptions(
            name='statistics',
            options={},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usertypes',
            options={},
        ),
        migrations.AddField(
            model_name='rules',
            name='rule_description',
            field=models.TextField(null=True),
        ),
    ]
