# Generated by Django 4.0.1 on 2022-06-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALEUser', '0009_alter_actions_options_alter_decision_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jid',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
