{
 "title": "WLAN_Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "script",
    "query": "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(\r\n    bucket: v.bucket,\r\n    tag: \"_measurement\",\r\n    predicate: (r) => true,\r\n    start: -1d\r\n)\r\n  |> filter(fn: (r) => r._value =~ /support_wlan.*/)"
   },
   {
    "name": "Client_MAC",
    "query": "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(\r\n    bucket: v.bucket,\r\n    tag: \"Client_MAC\",\r\n    predicate: (r) => true,\r\n    start: -1d\r\n)"
   }
  ]
 },
 "panels": [
  { "title": "Script Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "script" },
  {
   "title": "Script Activity per MAC Address",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"ALE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"support_wlan_association\" or r[\"_measurement\"] == \"support_wlan_dhcp\" or r[\"_measurement\"] == \"support_wlan_mac_auth\" or r[\"_measurement\"] == \"support_wlan_radius_auth\" or r[\"_measurement\"] == \"support_wlan_deassociation\")\r\n  |> filter(fn: (r) => r[\"Client_MAC\"] == \"$Client_MAC\")\r\n  |> aggregateWindow(every: 30s, fn: sum, timeSrc: \"_start\")"
    }
   ]
  },
  {
   "title": "Script Activity per MAC Address for WCF",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"ALE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"support_wlan_wcf\")\r\n  |> filter(fn: (r) => r[\"Client_MAC\"] == \"$Client_MAC\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "WLAN Deauthentication Reason Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"ALE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"support_wlan_deassociation\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "WLAN Deauth Pie Chart",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ALE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"support_wlan_deassociation\")\r\n  |> group(columns: [\"Reason_Deassociation\"])\r\n  |> filter(fn: (r) => r[\"topic\"] == \"deauth\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> count()"
    }
   ]
  },
  {
   "title": "WLAN Roaming Pie Chart",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ALE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"support_wlan_deassociation\")\r\n  |> group(columns: [\"Reason_Deassociation\"])\r\n  |> filter(fn: (r) => r[\"topic\"] == \"roaming\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> count()"
    }
   ]
  },
  {
   "title": "WLAN Leaving Pie Chart",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ALE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"support_wlan_deassociation\")\r\n  |> group(columns: [\"Reason_Deassociation\"])\r\n  |> filter(fn: (r) => r[\"topic\"] == \"leaving\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> count()"
    }
   ]
  }
 ]
}