INSERT INTO `ALEUser_usertypes` VALUES (1,'Admin');

INSERT INTO `ALEUser_usertypes` VALUES (2,'regular');


INSERT INTO `ALEUser_rulestypes` VALUES (1,'Default');

INSERT INTO `ALEUser_rulestypes` VALUES (2,'Custom');


INSERT INTO `ALEUser_decision` VALUES ('Yes');

INSERT INTO `ALEUser_decision` VALUES ('No');

INSERT INTO `ALEUser_decision` VALUES ('Yes and Remember');

-- INSERT INTO `ALEUser_actions` VALUES (1,'Increase log verbosity','','');
INSERT INTO `ALEUser_actions` VALUES (1,'Increase log verbosity','','');

-- INSERT INTO `ALEUser_actions` VALUES (2,'Send Notification','','');
INSERT INTO `ALEUser_actions` VALUES (2,'Send notification','','');

-- INSERT INTO `ALEUser_actions` VALUES (3,'Send File','','');
INSERT INTO `ALEUser_actions` VALUES (3,'Send file','','');

-- INSERT INTO `ALEUser_actions` VALUES (4,'Both','','');
INSERT INTO `ALEUser_actions` VALUES (4,'Collect log and send notification','','');

INSERT INTO `ALEUser_actions` VALUES (5,'Execute Scripts','','');


INSERT INTO `ALEUser_users` (email) SELECT email FROM auth_user WHERE id=1;

UPDATE `ALEUser_users` SET jid=@inputed_jid WHERE user_id=1;

UPDATE `ALEUser_users` SET type_id_id=1, user_name_id=1 WHERE user_id=1;


INSERT INTO `ALEUser_rules` VALUES(1,'if $msg contains \'Buffer list is empty\'',TRUE,5,1,1,'Step1/2 When a Network Loop is detected we increase the log verbosity of the task bcmd');

INSERT INTO `ALEUser_rules` VALUES(2,'if $msg contains \'slNi MACMOVE\' and $msg contains \'macCallBackProcessing\'',TRUE,5,3,1,'Step2/2 When a Network Loop is detected a notification is sent with the OmniSwitch IP Address/Hostname and interface/port number. The notification proposes remediation action (interface/port admin-state disable) for stopping the network loop. Log verbosity is set back to Info. Once action is complete, a notification with a summary and log collection is sent.');

INSERT INTO `ALEUser_rules` VALUES(3,'if $msg contains \'PMD generated at\'',TRUE,5,3,1,'Notification sent when a Core Dump is generated by an OmniSwitch task. Application is collecting the tech_support logs and core dump files.');

INSERT INTO `ALEUser_rules` VALUES(4,'if $msg contains \'pmnHALLinkStatusCallback:\'',TRUE,5,3,1,'Notification sent when a Port Flapping is observed on an OmniSwitch.  The notification proposes remediation action (interface/port admin-state disable) for stopping port flapping. Once action is complete, a notification with a summary and log collection is sent.');

INSERT INTO `ALEUser_rules` VALUES(5,'if $msg contains \'Denial of Service attack detected:\'',TRUE,5,1,1,'Step1/2 When a Denial Of Service Attack is detected we increase the log verbosity of the task ipv4.');

INSERT INTO `ALEUser_rules` VALUES(6,'if $msg contains \'ALV4 event: PSCAN\' or \$msg contains \'invalid ip from\' or \$msg contains \'loopback-src\'',TRUE,5,3,1,'Step2/2 When a Denial Of Service Attack is detected a notification with log collection is sent with the OmniSwitch IP Address/Hostname and interface/port number. The notification proposes remediation action (qos policy rule) for preventing network access. Log verbosity is set back to Info. Once action is complete, a notification with a summary and log collection is sent.');

INSERT INTO `ALEUser_rules` VALUES(7,'if $msg contains \'SES AAA\' and $msg contains \'Failed\'',TRUE,5,2,1,'Notification sent when an authentication failure is noticed on an OmniSwitch. Notification contains the source protocol and user login.');

INSERT INTO `ALEUser_rules` VALUES(8,'if $msg contains \'Storm Threshold violation\'',TRUE,5,3,1,'Notification sent when a Traffic Storm  is noticed on an OmniSwitch. This event is triggered when an unexpected traffic (unknown unicast, multicast, broadcast) exceeds the flood-limit threshold. The notification proposes remediation action (interface/port admin-state disable) for stopping the storm. Once action is complete, a notification with a summary and log collection is sent.');

INSERT INTO `ALEUser_rules` VALUES(9,'if $msg contains \'Violation set\' or $msg contains \'in violation\'',TRUE,5,3,1,'Notification sent when a port violation  is noticed on an OmniSwitch. The notification contains the OmniSwitch IP Address/Hostname, interface/port number, violation reason (LBD, QOS, Ling Monitoring …). The notification proposes remediation action (clear violation port) for clearing the violation if unexpected. Once action is complete, a notification with a summary and log collection is sent.');

INSERT INTO `ALEUser_rules` VALUES(10,'if $msg contains \'Sending VC Takeover to NIs and applications\'',TRUE,5,2,1,'Notification sent when an action is executed on a Virtual Chassis (takeover, reload, unit down). The notification contains the OmniSwitch IP Address/Hostname, action, unit ID (depending of the use case)');

INSERT INTO `ALEUser_rules` VALUES(11,'if $msg contains \'The switch was restarted by\'',TRUE,5,2,1,'Notification sent when an action is executed on a Virtual Chassis (takeover, reload, unit down). The notification contains the OmniSwitch IP Address/Hostname, action, unit ID (depending of the use case)');

INSERT INTO `ALEUser_rules` VALUES(12,'if $msg contains \'bootMgrVCMTopoDataEventHandler\' and $msg contains \'no longer\'',TRUE,5,2,1,'Notification sent when an action is executed on a Virtual Chassis (takeover, reload, unit down). The notification contains the OmniSwitch IP Address/Hostname, action, unit ID (depending of the use case)');

INSERT INTO `ALEUser_rules` VALUES(13,'if $msg contains \'cmmEsmHandleNIDown\' and $msg contains \'chassis\'',TRUE,5,2,1,'Notification sent when an action is executed on a Virtual Chassis (takeover, reload, unit down). The notification contains the OmniSwitch IP Address/Hostname, action, unit ID (depending of the use case)');

INSERT INTO `ALEUser_rules` VALUES(14,'if $msg contains \'radCli\' and $msg contains \'RADIUS\'',TRUE,5,2,1,'Notification sent when Radius Healtcheck noticed the radius server is unreachable. The notification contains the OmniSwitch IP Address/Hostname, concerned Radius profile');

INSERT INTO `ALEUser_rules` VALUES(15,'if $msg contains \'ADJACENCY INFO: Lost L1 adjacency\'',TRUE,5,2,1,'Notification sent when SPB adjacent OmniSwitch is unreachable. The notification contains the OmniSwitch IP Address/Hostname, Adjacent OmniSwitch System ID, interface/port number');

INSERT INTO `ALEUser_rules` VALUES(16,'if $msg contains \'OSPF neighbor state change\'',TRUE,5,2,1,'Notification sent when OSPF interface status is updated. The notification contains the OmniSwitch IP Address/Hostname, Neighbor IP Address');

INSERT INTO `ALEUser_rules` VALUES(17,'if $msg contains \'bgp\' and $msg contains \'transitioned to\'',TRUE,5,2,1,'Notification sent when BGP interface status is updated. The notification contains the OmniSwitch IP Address/Hostname, BGP Peer IP Address');

INSERT INTO `ALEUser_rules` VALUES(18,'if $msg contains \'cmmEsmCheckDDMThresholdViolations\'',TRUE,5,3,1,'Notification sent when Digital Diagnostics Monitoring exceeds the threshold. The notification contains the OmniSwitch IP Address/Hostname, SFP interface/port number, the alarm type and value');

INSERT INTO `ALEUser_rules` VALUES(19,'if $msg contains \'TARGET ASSERTED\'',TRUE,5,2,1,'Notification sent when unhandled exception occurred on WLAN Stellar AP. Please contact ALE Customer Support');

INSERT INTO `ALEUser_rules` VALUES(20,'if $msg contains \'Internal error\'',TRUE,5,2,1,'Notification sent when unhandled exception occurred on WLAN Stellar AP. Please contact ALE Customer Support');

INSERT INTO `ALEUser_rules` VALUES(21,'if $msg contains \'sysreboot\' and $msg contains \'Power Off\'',TRUE,5,2,1,'Notification sent when an unexpected reboot is detected on WLAN Stellar AP. Please check the lanpower status on OmniSwitch');

INSERT INTO `ALEUser_rules` VALUES(22,'if $msg contains \'sysreboot\'',TRUE,5,2,1,'Notification sent when a manual reboot is done on WLAN Stellar AP');

INSERT INTO `ALEUser_rules` VALUES(23,'if $msg contains \'osupgrade\' and \'sysupgrade\'',TRUE,5,2,1,'Notification sent when a manual upgrade is done on WLAN Stellar AP. The notification contains the WLAN Stellar AP IP Address and the release upgrade');

INSERT INTO `ALEUser_rules` VALUES(24,'if $msg contains \'Fatal exception\' or $msg contains \'Kernel panic\' or $msg contains \'KERNEL PANIC\' or $msg contains \'Exception stack\' or $msg contains \'parse condition rule is error\' or $msg contains \'core-monitor reboot\'',TRUE,5,2,1,'Notification sent when unhandled exception occurred on WLAN Stellar AP. Please contact ALE Customer Support');

INSERT INTO `ALEUser_rules` VALUES(25,'if $msg contains \'Unable to handle kernel\'',TRUE,5,2,1,'Notification sent when unhandled exception occurred on WLAN Stellar AP. Please contact ALE Customer Support');

INSERT INTO `ALEUser_rules` VALUES(26,'if $msg contains \'ChassisSupervisor\' and $msg contains \'Alert\'',TRUE,5,2,1,'Notification sent when an hardware defect or operation is noticed on OmniSwitch. The notification contains the OmniSwitch IP Address/Hostname and Power Supply ID');

INSERT INTO `ALEUser_rules` VALUES(27,'if $msg contains \'ChassisSupervisor\' and $msg contains \'ERR\'',TRUE,5,2,1,'Notification sent when an hardware defect or operation is noticed on OmniSwitch. The notification contains the OmniSwitch IP Address/Hostname and Power Supply ID');

INSERT INTO `ALEUser_rules` VALUES(28,'if $msg contains \'ChassisSupervisor\' and $msg contains \'ALRT\'',TRUE,5,2,1,'Notification sent when an hardware defect or operation is noticed on OmniSwitch. The notification contains the OmniSwitch IP Address/Hostname and Power Supply ID');

INSERT INTO `ALEUser_rules` VALUES(29,'if $msg contains \'ChassisSupervisor\' and $msg contains \'Removed\'',TRUE,5,2,1,'Notification sent when an hardware defect or operation is noticed on OmniSwitch. The notification contains the OmniSwitch IP Address/Hostname and Power Supply ID');

INSERT INTO `ALEUser_rules` VALUES(30,'if $msg contains \'ChassisSupervisor\' and $msg contains \'inoperable\'',TRUE,5,2,1,'Notification sent when an hardware defect or operation is noticed on OmniSwitch. The notification contains the OmniSwitch IP Address/Hostname and Power Supply ID');

INSERT INTO `ALEUser_rules` VALUES(31,'if $msg contains \'ChassisSupervisor\' and $msg contains \'UNPOWERED\'',TRUE,5,2,1,'Notification sent when an hardware defect or operation is noticed on OmniSwitch. The notification contains the OmniSwitch IP Address/Hostname and Power Supply ID');

INSERT INTO `ALEUser_rules` VALUES(32,'if $msg contains \'FAULT State change\'',TRUE,5,3,1,'Notification sent when LANPOWER port in Denied or Fault status is noticed on OmniSwitch. The notification contains the OmniSwitch IP Address/Hostname, port in faulty state and reason. The notification proposes remediation action (lanpower disable or lanpower reload). Once action is complete, a notification with a summary and log collection is sent.');

INSERT INTO `ALEUser_rules` VALUES(33,'if $msg contains \'Receive agg port leave request\' and not \($msg contains \'Port Leave\'\)',TRUE,5,3,1,'Notification sent when a LinkAgg Port Leave is noticed on OmniSwitch. Reason could be a connectivity issue or no LACP frame received within the time range. The notification contains the OmniSwitch IP Address/Hostname and Aggregate ID');

INSERT INTO `ALEUser_rules` VALUES(34,'if $msg contains \'duplicate IP address\' or $msg contains \'Duplicate IP address\' or $msg contains \'arp info overwritten\'',TRUE,5,3,1,'Notification sent when a Duplicate IP Address is noticed on the OmniSwitch. The notification contains the OmniSwitch IP Address/Hostname and duplicate IP Address. The notification proposes remediation action (QOS Policy) to block the traffic from duplicate IP Address. If duplicate IP Address is an Essential IP Address (listed in the Essential_IP.csv file) or the corresponding MAC Address matches with an OmniSwitch device, the action is aborted. Once action is complete, a notification with a summary and log collection is sent.');

INSERT INTO `ALEUser_rules` VALUES(35,'if $msg contains \'Unable to connect\' and $msg contains \'mqttd\'',TRUE,5,3,1,'Notification sent when an OmniSwitch with device-profiling enabled (aka IoT Profiling) cannot contact the OmniVista. Reason could be a connectivity issue or configuration issue. The notification contains the OmniSwitch IP Address/Hostname and OmniVista IP Address');

INSERT INTO `ALEUser_rules` VALUES(36,'if $msg contains \'stpCmm\' and $msg contains \'may not be stp enabled\'',TRUE,5,3,1,'Notification sent when an OmniSwitch with Spanning-Tree Running Mode is per VLAN has detected the STP is not enabled for that VLAN');

INSERT INTO `ALEUser_rules` VALUES(37,'if $msg contains \'ospf\' and $msg contains \'oversized LSA\'',TRUE,5,3,1,'Notification sent when an OmniSwitch detects the OSPF neighbor status is stuck into Load state as LSA received from Neighbor oversizes the MTU value. Note that as of AOS 8.5.R01 OmniSwitch fragments the OSPF LSAs packet when it crosses the outgoing IP interface MTU size');

INSERT INTO `ALEUser_rules` VALUES(38,'if $msg contains \'TCAM_RET_NOT_FOUND\'',TRUE,5,2,1,'Notification sent when an OmniSwitch detects an exception when loading the QOS Policy Rules');

INSERT INTO `ALEUser_rules` VALUES(39,'if $msg contains \'saaCMM\'',TRUE,5,3,1,'Notification sent when an OmniSwitch receives a Service Assurance Agent status/Iteration packet loss');

INSERT INTO `ALEUser_rules` VALUES(40,'if $msg contains \'OPENVPN\' and $msg contains \'Fatal TLS error\'',TRUE,5,3,1,'Notification sent when an OmniSwitch OPENVPN Tunnel does not establish because of TLS error');

INSERT INTO `ALEUser_rules` VALUES(41,'if $msg contains \'OPENVPN\' and $msg contains \'ETIMEDOUT\'',TRUE,5,3,1,'Notification sent when an OmniSwitch cannot reach the OV Cirrus Activation Server');

INSERT INTO `ALEUser_rules` VALUES(42,'if $msg contains \'OPENVPN\' and $msg contains \'EHOSTUNREACH\'',TRUE,5,3,1,'Notification sent when an OmniSwitch cannot reach the OV Cirrus Activation Server');

INSERT INTO `ALEUser_rules` VALUES(43,'if $msg contains \'ovcmm\' and $msg contains \'Invalid process status\'',TRUE,5,3,1,'Notification sent when an OmniSwitch contacted the OV Cirrus Activation Server but Serial Number does not exist into the Device Catalog');

INSERT INTO `ALEUser_rules` VALUES(44,'if $msg contains \'openvpn\' and $msg contains \'Cannot resolve host address\'',TRUE,5,3,1,'Notification sent when an OmniSwitch cannot resolve the OV Cirrus Activation Server FQDN');

INSERT INTO `ALEUser_rules` VALUES(45,'if $msg contains \'temperature read failed\'',TRUE,5,3,1,'A Fan unit is Down or running abnormal on OmniSwitch. These kind of issues are mostly created due to Faulty or Non-ALE certified SFP and QSFP. If the issue is still seen after using a good ALE-Certified SFP and QSFP, ugrade the CPUCPLD may resolve this issue');

INSERT INTO `ALEUser_rules` VALUES(46,'if $msg contains \'Incompatible expansion module\'',TRUE,5,3,1,'A NI module hardware unit is Down or running abnormal on OmniSwitch.');

INSERT INTO `ALEUser_rules` VALUES(47,'if $msg contains \'healthCmm\' and $msg contains \'rising above\'',TRUE,5,3,1,'OmniSwitch is running into HIGH CPU');

INSERT INTO `ALEUser_rules` VALUES(48,'if $msg contains \'The top 20\'',TRUE,5,3,1,'OmniSwitch is running into HIGH MEMORY');

INSERT INTO `ALEUser_rules` VALUES(49,'if $msg contains \'Add black list mac\'',TRUE,5,2,1,'WLAN Stellar AP - WLAN WIPS Detects a WLAN Attack and as per policy is adding the Clients MAC Address into the BlackList');

INSERT INTO `ALEUser_rules` VALUES(50,'if $msg contains \'status 37\'',TRUE,5,2,1,'WLAN Stellar AP - Clients MAC Address is blocked by WLAN Access List');

INSERT INTO `ALEUser_rules` VALUES(51,'if $msg contains \'The vlan counts reach the maximum\'',TRUE,5,3,1,'WLAN Stellar AP - The maximum of vlan allowed on this Stellar AP is reached');

INSERT INTO `ALEUser_rules` VALUES(52,'if $msg contains \'STA limit reached\'',TRUE,5,3,1,'WLAN Stellar AP - The maximum of WLAN association allowed on the BSSID (SSID and Band) is reached');

INSERT INTO `ALEUser_rules` VALUES(53,'if $msg contains \'current time is not allowed\'',TRUE,5,2,1,'WLAN Stellar AP - Client cannot associate to SSID because of Period Policy');

INSERT INTO `ALEUser_rules` VALUES(54,'if $msg contains \'Loaction Policy\' and $msg contains \'check Failed\'',TRUE,5,2,1,'WLAN Stellar AP - Client cannot associate to SSID because of Location Policy');


INSERT INTO `ALEUser_settings_value` VALUES (1,@companyname,'{\"ssh_port\": 2222, \"grafana_port\": 3000, \"rsyslog_port\": 10514}');
