#!/usr/bin/env python3

import sys
import os
import json
from time import strftime, localtime
#import smtplib
#import mimetypes
import re
from support_tools_OmniSwitch import get_credentials, get_tech_support_sftp, get_pmd_file_sftp
from support_send_notification import *
import time

_runtime = strftime("%Y-%m-%d %H:%M:%S", localtime())

from pattern import set_rule_pattern, set_portnumber, set_decision, mysql_save

path = os.path.dirname(__file__)
print(os.path.abspath(os.path.join(path,os.pardir)))
sys.path.insert(1,os.path.abspath(os.path.join(path,os.pardir)))
from alelog import alelog

# Example of JSON content
#### {"@timestamp":"2021-11-10T09:42:02.867257+01:00","type":"syslog_json","relayip":"10.130.7.244","hostname":"OS6860N","message":"10:55:46.686 OS6860E-Core2 swlogd COREDUMPER  ALRM: Dumping core for task dpcmm","end_msg":""}
### {"@timestamp":"2021-11-10T09:42:02.867257+01:00","type":"syslog_json","relayip":"10.130.7.244","hostname":"OS6860N","message":"OS6860E-Core2 swlogd PMD main ALRT: PMD generated at /flash/pmd/pmd-agCmm-12.29.2020-11.26.28","end_msg":""}

# Variables
filename = 'tech_support_complete.tar'
filename_pmd = '/flash/pmd/pmd-xx'

script_name = sys.argv[0]
runtime = strftime("%d_%b_%Y_%H_%M_%S", localtime())

uname = os.system('uname -a')
os.system('logger -t montag -p user.info Executing script ' + script_name)

pattern = sys.argv[1]
print(pattern)
set_rule_pattern(pattern)

switch_user, switch_password, mails, jid1, jid2, jid3, ip_server, login_AP, pass_AP, tech_pass, random_id, company, room_id = get_credentials()

# Function called when Core Dump is observed
def pmd_issue(ipadd, jid1, jid2, jid3):
    os.system('logger -t montag -p user.info PMD Script - A Core DUMP is generated by switch: ' + ipadd[1])
    info = "Preventive Maintenance Application - A Core DUMP is generated by OmniSwitch {0} / {1}".format(host,ipadd)
    set_decision(ipadd, "1")
    send_alert_detailed(info, jid1, jid2, jid3, 'LAN - Core DUMP rule', 'Status: Alert Sent', company)
    mysql_save(runtime=_runtime, ip_address=ipadd, result='success', reason=info, exception='')
 
def extract_ipadd():
    last = ""
    with open("/var/log/devices/lastlog_pmd.json", "r", errors='ignore') as log_file:
        for line in log_file:
            last = line

    with open("/var/log/devices/lastlog_pmd.json", "w", errors='ignore') as log_file:
        log_file.write(last)

    with open("/var/log/devices/lastlog_pmd.json", "r", errors='ignore') as log_file:
        log_json = json.load(log_file)
        ipadd = log_json["relayip"]
        host = log_json["hostname"]
        ipadd = str(ipadd)
        message_reason = log_json["message"]
        l = []
        l.append('/code ')
        l.append(message_reason)
        message_reason = ''.join(l)
        print(ipadd)
    return ipadd, host, message_reason


def extract_pmd_path():
    last = ""
    with open("/var/log/devices/lastlog_pmd.json", "r", errors='ignore') as log_file:
        for line in log_file:
            last = line

    with open("/var/log/devices/lastlog_pmd.json", "w", errors='ignore') as log_file:
        log_file.write(last)

    with open("/var/log/devices/lastlog_pmd.json", "r", errors='ignore') as log_file:
        try:
            log_json = json.load(log_file)
            ipadd = log_json["relayip"]
            host = log_json["hostname"]
            message_reason = log_json["message"]
            l = []
            l.append('/code ')
            l.append(message_reason)
            message_reason = ''.join(l)
            print(ipadd)
        except json.decoder.JSONDecodeError:
            print("File /var/log/devices/lastlog_pmd.json empty")
            exit()
        except IndexError:
            print("Index error in regex")
            exit()
        try:
            filename_pmd = re.findall(r"PMD generated at (.*)", message_reason)[0]
            if "flash" in filename_pmd:
                appid = re.findall(r"pmd-(.*)-",filename_pmd)[0]
                pattern = r'[0-9]'
                appid = re.sub(pattern, '', appid)
                appid = appid.replace('-..',"",2)
                print(appid)
            print(filename_pmd)
        except IndexError:
            print("Index error in regex")
            exit()
        print(filename_pmd)
    return filename_pmd, message_reason, appid


print("Core DUMP - call function collecting log")

ipadd, host, message_reason = extract_ipadd()

set_portnumber("0")
set_decision(ipadd, "2")
if alelog.rsyslog_script_timeout(ipadd + host + pattern, time.time()):
    print("Less than 5 min")
    exit(0)

### Notification Rainbow ###
pmd_issue(ipadd, jid1, jid2, jid3)

### TECH-SUPPORT ENG COMPLETE ###
get_tech_support_sftp(switch_user, switch_password, host, ipadd)

### get PMD FILE ###
print("Starting collecting PMD file")
filename_pmd, message_reason, appid = extract_pmd_path()
filename_path = get_pmd_file_sftp(switch_user, switch_password, ipadd, filename_pmd)

if jid1 != '' or jid2 != '' or jid3 != '':
    subject = ("Preventive Maintenance Application - A Core DUMP is generated by OmniSwitch {0} / {1} on function {2}").format(host, ipadd, appid)
    action = ("A Core DUMP is generated by OmniSwitch {0} / {1} on function {2} - Tech-support eng complete and PMD files are collected and stored in server {0}").format(host, ipadd, appid,ip_server)
    result = "Please contact ALE Customer Support team."
    send_message_detailed(action, jid1, jid2, jid3)
    #send_message_detailed(message_reason, jid1, jid2, jid3)

sys.exit(0)
