{
 "title": "OmniSwitch Health Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "IP", "query": { "query": "label_values(ip)" } },
   {
    "name": "Name",
    "query": {
     "query": "label_values(MEM{ip=\"$IP\"}, name)"
    }
   },
   {
    "name": "Chassis",
    "query": {
     "query": "label_values(CPU{ip=\"$IP\"},chassis)"
    }
   },
   {
    "name": "Slot",
    "query": {
     "query": "label_values(CPU{chassis=\"$Chassis\", ip=\"$IP\"},slot)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "L2 Entries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "IP",
   "collapsed": true
  },
  {
   "title": "ARP Entries",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ARP_Entries{ip=\"$IP\",name=\"$Name\"}"
    }
   ]
  },
  {
   "title": "MAC Learning Entries",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MAC_Learning_Bridging_Entries{ip=\"$IP\",name=\"$Name\"}",
     "legendFormat": "Bridging"
    },
    {
     "expr": "MAC_Learning_Servicing_Entries{ip=\"$IP\",name=\"$Name\"}",
     "legendFormat": "Servicing"
    },
    {
     "expr": "MAC_Learning_Filtering_Entries{ip=\"$IP\",name=\"$Name\"}",
     "legendFormat": "Filtering"
    }
   ]
  },
  {
   "title": "UNP User Entries (Bridge port)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "UNP_User_Active_Entries{ip=\"$IP\",name=\"$Name\"}",
     "legendFormat": "Bridging"
    },
    {
     "expr": "UNP_User_Block_Entries{ip=\"$IP\",name=\"$Name\"}",
     "legendFormat": "Filtering"
    },
    {
     "expr": "UNP_User_Total_Entries{ip=\"$IP\",name=\"$Name\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Topk 5 OmniSwitches with ARP Entries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "topk(5,ARP_Entries)", "legendFormat": "{{ip}}" }
   ]
  },
  {
   "title": "Topk 5 OmniSwitches with MAC Learning Entries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,MAC_Learning_Bridging_Entries)",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Ratio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MAC_Learning_Filtering_Ratio_Entries{ip=\"$IP\",name=\"$Name\"}",
     "legendFormat": "Filtering Ratio"
    },
    {
     "expr": "UNP_User_Ratio_Entries{ip=\"$IP\",name=\"$Name\"}",
     "legendFormat": "UNP User Block Ratio"
    }
   ]
  },
  {
   "title": "UNP User Ratio Block vs Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Active",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "UNP_User_Ratio_Entries",
     "group": { "alias": "Active", "name": "test", "url": "" },
     "legendFormat": "{{ip}} / {{name}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Topk 5 MAC Learning Ratio Filtering vs Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Active",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "topk(5,MAC_Learning_Filtering_Ratio_Entries)",
     "group": { "alias": "Active", "name": "test", "url": "" },
     "legendFormat": "{{ip}} / {{name}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  { "title": "L3 Entries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "IP" },
  {
   "title": "Routing Table Summary",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Routing_Table_Local_Entries{ip=\"$IP\",name=\"$Name\"}",
     "legendFormat": "LOCAL"
    },
    {
     "expr": "Routing_Table_Static_Entries{ip=\"$IP\",name=\"$Name\"}",
     "legendFormat": "STATIC"
    },
    {
     "expr": "Routing_Table_Ospf_Entries{ip=\"$IP\",name=\"$Name\"}",
     "legendFormat": "OSPF"
    },
    {
     "expr": "Routing_Table_Ibgp_Entries{ip=\"$IP\",name=\"$Name\"}",
     "legendFormat": "IBGP"
    },
    {
     "expr": "Routing_Table_Ebgp_Entries{ip=\"$IP\",name=\"$Name\"}",
     "legendFormat": "EBGP"
    }
   ]
  },
  {
   "title": "Topk 3 OmniSwitches with Routing Entries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3,Routing_Table_Total_Entries)",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  { "title": "Gauge real time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "CPU real time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "CPU{chassis=\"$Chassis\",ip=\"$IP\",name=\"$Name\",slot=\"$Slot\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Temp real time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TEMP{chassis=\"$Chassis\",ip=\"$IP\",name=\"$Name\"}"
    }
   ]
  },
  {
   "title": "Memory real time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MEM{name=\"$Name\", chassis=\"$Chassis\", ip=\"$IP\", slot=\"$Slot\"}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Global Memory (topk 5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    { "expr": "topk(5,MEM)", "legendFormat": "{{ip}}" }
   ]
  },
  {
   "title": "Details Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "MEM{chassis=\"$Chassis\",ip=\"$IP\",name=\"$Name\",slot=\"$Slot\"}",
     "legendFormat": "{{name}} -- {{chassis}}/{{slot}} ({{ip}})"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Global temperature (topk 5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "topk(5,TEMP)", "legendFormat": "{{ip}}" }
   ]
  },
  {
   "title": "Details Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "TEMP{chassis=\"$Chassis\",ip=\"$IP\",name=\"$Name\"}",
     "legendFormat": "{{name}} -- {{chassis}} ({{ip}})"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Global CPU (topk 5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    { "expr": "topk(5,CPU)", "legendFormat": "{{ip}}" }
   ]
  },
  {
   "title": "Details CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "CPU{name=\"$Name\", chassis=\"$Chassis\", ip=\"$IP\", slot=\"$Slot\"}",
     "legendFormat": "{{name}} -- {{chassis}} / {{slot}} ({{ip}})"
    }
   ]
  }
 ]
}